# Generated by Django 3.1 on 2020-09-05 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellerCenter', '0002_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.CharField(db_column='CITY_ID', max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='NAME', max_length=255)),
                ('code', models.CharField(db_column='CODE', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='DELETED_AT', null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='discount',
            new_name='promo_price',
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_fee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DeliveryFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(db_column='AMOUNT')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='DELETED_AT', null=True)),
                ('city', models.ForeignKey(db_column='CITY_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='sellerCenter.city')),
                ('sku', models.ForeignKey(db_column='SKU', on_delete=django.db.models.deletion.DO_NOTHING, to='sellerCenter.product')),
            ],
        ),
    ]
