# Generated by Django 3.1 on 2020-09-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerCenter', '0003_auto_20200905_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_fee',
            field=models.ManyToManyField(related_name='delivery_fee', through='sellerCenter.DeliveryFee', to='sellerCenter.City'),
        ),
    ]
