# Generated by Django 3.1 on 2020-09-13 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerCenter', '0006_auto_20200913_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='barcode',
            field=models.ImageField(default=None, upload_to='sellerCenter/barecode/%y/%m/%d'),
        ),
    ]
