# Generated by Django 3.1 on 2020-09-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerCenter', '0007_order_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to='sellerCenter/barecode/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to='sellerCenter/barecode/%y/%m/%d'),
        ),
    ]
