# Generated by Django 3.1 on 2020-09-20 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sellerCenter', '0009_auto_20200913_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referal',
            fields=[
                ('referal_id', models.CharField(db_column='REFERAL_ID', max_length=255, primary_key=True, serialize=False)),
                ('link', models.CharField(db_column='LINK', max_length=255)),
                ('is_active', models.BooleanField(db_column='IS_ACTIVE', default=True)),
                ('sku', models.ForeignKey(db_column='SKU', on_delete=django.db.models.deletion.DO_NOTHING, to='sellerCenter.product')),
                ('user', models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'referal',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='referal',
            field=models.ForeignKey(db_column='REFERAL_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sellerCenter.referal'),
        ),
    ]
