# Generated by Django 3.1 on 2020-09-22 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellerCenter', '0011_auto_20200920_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referal',
            old_name='sku',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='referal',
            old_name='user',
            new_name='seller',
        ),
    ]
